name: Python package

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
        os: [macos-10.15, windows-2016]

    steps:
      - uses: actions/checkout@v1
      - name: build with pyinstaller
        run: |
          pip3 install pyinstaller
          pyinstaller --onefile wallet.py --name wallet-app

      - uses: actions/upload-artifact@master
        with:
          name: artifacts-${{ matrix.os }}
          path: dist/

  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        python-version: [3.7, 3.8]
        os: [macos-10.15, windows-2016]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Installing pip packages
      run: |
        pip install --upgrade pip
        pip install pylint
        pip install pytest
    - name: Lint code with pylint
      run: pylint *.py
    - name: Run tests with pytest
      run: |
        pytest

  Build-and-Push-Docker-Image:
    runs-on: ubuntu-latest
    needs: test
    name: Docker Build, Tag, Push

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Download built artifact
      uses: actions/download-artifact@main
      with:
        name: artifacts-${{ matrix.os }}
        path: public
    - name: Build container image
      uses: docker/build-push-action@v1
      with:
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
        registry: docker.pkg.github.com
        repository: koushi0194/github-actions-for-packages/test-action
        tag_with_sha: true
