name: Python package

on: [push]

jobs:
  build:

    runs-on: [macos-10.15]
    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Lint code with pylint
      run: |
        pip install pylint
        pip install pytest
        pylint *.py
    - name: Run tests with pytest
      run: |
        pytest
